# Generated by Django 5.2.3 on 2025-06-29 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='learninggoal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learningpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learningsession',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='learning.learninggoal'),
        ),
        migrations.AddField(
            model_name='learningsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='progress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resource',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='learning.subject'),
        ),
        migrations.AddField(
            model_name='progress',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.subject'),
        ),
        migrations.AddField(
            model_name='learningpreference',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.subject'),
        ),
        migrations.AddField(
            model_name='learninggoal',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.subject'),
        ),
        migrations.AddField(
            model_name='topic',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='learning.subject'),
        ),
        migrations.AddField(
            model_name='resource',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='learning.topic'),
        ),
        migrations.AddField(
            model_name='progress',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.topic'),
        ),
        migrations.AddField(
            model_name='learningpreference',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.topic'),
        ),
        migrations.AddField(
            model_name='learninggoal',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.topic'),
        ),
        migrations.AddField(
            model_name='userresource',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_resources', to='learning.resource'),
        ),
        migrations.AddField(
            model_name='userresource',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_resources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('subject', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='progress',
            unique_together={('user', 'subject', 'topic')},
        ),
        migrations.AlterUniqueTogether(
            name='userresource',
            unique_together={('user', 'resource')},
        ),
    ]
