# Generated by Django 5.2.4 on 2025-08-04 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0003_roadmap_roadmapstep'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoadmapStep',
        ),
    ]
