# Generated by Django 5.2.4 on 2025-08-04 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0004_delete_roadmapstep'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Roadmap',
            new_name='RoadmapTopic',
        ),
    ]
