# Generated by Django 5.2.5 on 2025-08-08 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0006_userroadmap'),
    ]

    operations = [
    ]
