# Generated by Django 5.2.4 on 2025-08-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0007_auto_20250808_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmaptopic',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, to='roadmap.roadmaptopic'),
        ),
    ]
