# Generated by Django 5.2.5 on 2025-09-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0008_roadmaptopic_prerequisites'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplan',
            name='purpose_of_study',
            field=models.CharField(choices=[('competitive_exam', 'Competitive Exam'), ('scoring', 'Scoring'), ('skill_gaining', 'Skill Gaining')], default='skill_gaining', max_length=50),
        ),
    ]
