# Generated by Django 5.2.4 on 2025-10-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0009_studyplan_purpose_of_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyplan',
            name='purpose_of_study',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
