# Generated by Django 5.2.4 on 2025-10-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0010_alter_studyplan_purpose_of_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyplan',
            name='purpose_of_study',
            field=models.CharField(choices=[('academics', 'Academics'), ('competitive_exam', 'Competitive Exam'), ('skill_development', 'Skill Development'), ('career_change', 'Career Change'), ('personal_interest', 'Personal Interest'), ('professional_certification', 'Professional Certification'), ('interview_preparation', 'Interview Preparation'), ('teaching_preparation', 'Teaching Preparation'), ('research', 'Research'), ('other', 'Other')], default='personal_interest', help_text='Select the primary purpose for your study plan', max_length=50),
        ),
    ]
